<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="style.css" type="text/css">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Formulaire</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="css/mdb.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/style.css">
  <link href="css/bootstrap-4-navbar.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Rock+Salt&display=swap" rel="stylesheet">
</head>


<body>
  <header>
    <h1> Bon de Commande </h1>
  </header>

</body>

</html>